name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: Win64
          - os: ubuntu-latest
            target: Android64
          - os: ubuntu-latest
            target: Android32

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Clear CPM cache
        run: rm -rf cpm-cache
        shell: bash

      - name: Use older, compatible Android NDK
        if: runner.os == 'Linux'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: true

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.target }}

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: coop-mod-${{ matrix.target }}
          path: build/*.geode
